---
title: "Project 1"
format: html
editor: visual
---

### Part 1 Data Processing 

#### Parsing Variable Values

```{r}
# Load the required packages
library(httr)
library(jsonlite)

#function to fetch the JSON for a single year
get_json_dict <- function(year) {
  # Construct the specific URL for the given year
  url <- paste0("https://api.census.gov/data/", year, "/acs/acs1/pums/variables.json")
  
  #GET() to pull the data
  response <- GET(url)
  
  # Extract and parse from JSON into an R list
  parsed <- fromJSON(content(response, as = "text", encoding = "UTF-8"))
  
  # Return 'variables'
  return(parsed$variables)

}

#filter the list
filter_census <- function(full_list, year) {
  #core variables
  core_vars <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", 
                 "JWMNP", "PWGTP", "FER", "HHL", "SCH", 
                 "SCHL", "SEX", "REGION", "DIVISION")
  
  # The state variable
  if (year %in% c(2021, 2022)) {
    state_var <- "ST"
  } else {
    state_var <- "STATE"
  }
  
  # Combine core variables
  target_vars <- c(core_vars, state_var)
  
  #keep only the variables whose names match our target list
  filtered_list <- full_list[names(full_list) %in% target_vars]
  
  return(filtered_list)
}


#save the data for all required years
years <- c(2021, 2022, 2023, 2024)

# Create an empty list
census_dicts <- list()

# Loop through each year
for (y in years) {
  raw_list <- get_json_dict(y)
  
  filtered_list <- filter_census(raw_list, y)
  
  #Store List
  census_dicts[[as.character(y)]] <- filtered_list
}

# Save the final combined list as an .rds file 
saveRDS(census_dicts, file = "data/census.rds")

#readRDS("data/census.rds")

```

#### Parsing API Data


```{r}
my_api_key <- "c6758c38f49e633cc5c6631c8251876e5bc70c58"

example_url <- "https://api.census.gov/data/2024/acs/acs1/pums?get=SEX,PWGTP,MAR&for=state:*&SCHL=24&key=c6758c38f49e633cc5c6631c8251876e5bc70c58"


response <- GET(example_url)
response

str(response)

parsed_census <- fromJSON(response)

```

